### ISSUE TITLE
Reconstruct image fail.

### ISSUE THREAD

**Issue by yuxu915** [garibida/ReNoise-Inversion#2] opened 2024-04-23 10:42 UTC
Hi, very good work and thanks for open source code!
I use `inversion_example_sdxl.py` to reconstruct the image of lion:
![image](https://github.com/garibida/ReNoise-Inversion/assets/94051337/2f3155e2-24b0-407d-8195-7f7524d5f70b)

but get results like:
![image](https://github.com/garibida/ReNoise-Inversion/assets/94051337/aa536208-892b-4323-ab56-5b94ae0cda99)

All settings are as default.
Would you please give me some suggestions?
Thanks.

**Comment by garibida** [comment] 2024-04-23 11:29
Hi, 
What model and scheduler do you use? Do you use my examples?
If your code is short and you can share it, it will be easier for me to help :)

**Comment by yuxu915** [comment] 2024-04-23 12:29
hi, I use:
```
model_type = Model_Type.SDXL
scheduler_type = Scheduler_Type.DDIM
```
I didn't modify anything in ` inversion_example_sdxl.py`.

**Comment by yuxu915** [comment] 2024-04-24 06:59
hi, @garibida , I've also test `inversion_example_turbo.py` and get similar fail results like:
![image](https://github.com/garibida/ReNoise-Inversion/assets/94051337/4a0df493-1688-4edf-bc48-3c340f1407aa)

However, I test `inversion_example_sd.py` , get successful results.
The problem seems to be present in the SDXL model. Would you please check it? 
Thank you.

**Comment by garibida** [comment] 2024-05-07 09:32
Hi,

Did you use the environment.yaml or requirements.txt to create your environment? I created multiple environments and I wasn't able to reproduce this issue...

**Comment by ajrheng** [comment] 2024-05-28 03:30
I had the same problem initially using my own environment and libraries, but creating the environment using `environment.yaml` solved the issue. Strange that slightly different versions of pytorch/diffusers can cause the model to fail completely.

**Comment by haofanwang** [comment] 2024-06-04 10:53
It's related to diffusers version. A newer version has some differences.

**Comment by haofanwang** [comment] 2024-06-04 12:29
I found the reason. The core difference is in the [pipeline_stable_diffusion_xl_img2img.py](https://github.com/huggingface/diffusers/blob/v0.24.0-release/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py) between 0.24.0 and latest versions. You can load the pipeline from 0.24.0 and then everything goes well.

To be more clear, there is a typo in 0.24.0, and it has been fixed in following updates.

In latest version,

```
timesteps, num_inference_steps = self.get_timesteps(
            num_inference_steps,
            strength,
            device,
            denoising_start=self.denoising_start if denoising_value_valid(self.denoising_start) else None,
        )
```

in 0.24.0

```
timesteps, num_inference_steps = self.get_timesteps(
            num_inference_steps,
            strength,
            device,
            denoising_start=self.denoising_start if denoising_value_valid else None,
        )
```

The denoising_start is different, which leads to different timesteps and noisy results.

**Closed** 2024-06-16 11:22 UTC

**Comment by yuxu915** [comment] 2024-07-09 02:49
@haofanwang hi, your answer perfectly solved my question, thank you!

> I found the reason. The core difference is in the [pipeline_stable_diffusion_xl_img2img.py](https://github.com/huggingface/diffusers/blob/v0.24.0-release/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py) between 0.24.0 and latest versions. You can load the pipeline from 0.24.0 and then everything goes well.
> 
> To be more clear, there is a typo in 0.24.0, and it has been fixed in following updates.
> 
> In latest version,
> 
> ```
> timesteps, num_inference_steps = self.get_timesteps(
>             num_inference_steps,
>             strength,
>             device,
>             denoising_start=self.denoising_start if denoising_value_valid(self.denoising_start) else None,
>         )
> ```
> 
> in 0.24.0
> 
> ```
> timesteps, num_inference_steps = self.get_timesteps(
>             num_inference_steps,
>             strength,
>             device,
>             denoising_start=self.denoising_start if denoising_value_valid else None,
>         )
> ```
> 
> The denoising_start is different, which leads to different timesteps and noisy results.
